### ISSUE TITLE
Bahslashamiz...

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#13]
Nega buni aynan `h2` olganizi..
![image](https://user-images.githubusercontent.com/99461357/163158855-67f2ee78-f3de-4eab-9763-afe9e5145031.png)
Buni esa aynan `h3` olganizi..
![image](https://user-images.githubusercontent.com/99461357/163159034-d82432f2-c52b-42d6-b8d9-35c7a5f24473.png)
Buni ham aynan  `h3` da olganizi to'liq izohlari bilan birga isbotlang...

### **Agar isbotlay olsangiz men ham nega aynan siz tutgan yo'l xato ekanini isbotlayman !**

**Comment by akramjonnuriddinov** [comment]
1. h1 ichida link qilish yoki linkni o'zini qoldirish mumkin ekan. Man linkni o'zini qoldirdim. ⚠️ 
2. Shu section nomi h2 da bo'ladi va bu narsa hozir bizga ko'rinmayapti. Shuning uchun cardlar section ichida bo'lgani uchun card-title darajasi bittaga pasayib h3 bo'ladi.

**Comment by MIRZOULUGBEK9008** [comment]
> 1. h1 ichida link qilish yoki linkni o'zini qoldirish mumkin ekan. Man linkni o'zini qoldirdim. ⚠️
> 2. Shu section nomi h2 da bo'ladi va bu narsa hozir bizga ko'rinmayapti. Shuning uchun cardlar section ichida bo'lgani uchun card-title darajasi bittaga pasayib h3 bo'ladi.

Tushunalik rahmat Respect
