### ISSUE TITLE
"Dark Mode" ga o'tganida  `svg`  ikonkalarning rangi o'zgarmayapti.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#14]
![image](https://user-images.githubusercontent.com/99461357/163159722-2e0bb133-41f2-4daa-9d1b-bbbfb1173eb0.png)
![image](https://user-images.githubusercontent.com/99461357/163159769-c601de52-3f76-4df5-a71a-cda874b02b24.png)

**Comment by akramjonnuriddinov** [comment]
Bularni keyin o'rganamiz shunda o'zgaradigan qilamiz, yoki position bilan img sifatida berib o'zgaradigan qilamiz keyinchalik:)
