### ISSUE TITLE
`margin-bottom:;` ning qiymatii ko'payib ketgan..

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#15]
**Qizil** chiziqda berilgan joyning qiymati `margin-bottom: 45px;` bo'ladi sizda esa  `75px`  turibdi
![image](https://user-images.githubusercontent.com/99461357/163160268-6cf67e95-622a-4df8-b5bf-06507cab0eb8.png)

**Comment by akramjonnuriddinov** [comment]
`margin-bottom: 45px;` turibdi faqat ulga manfiy qiymatdagi margin berilgani uchun shunaqa ko'rinyapti. Agar `ul` ni davomidan ma'lumot kelsa 45px pastda turadi.
