### ISSUE TITLE
"detail.html" dagi  `h3` elementning stillari xato berilgan.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#19]
**Sizda**
![image](https://user-images.githubusercontent.com/99461357/163165929-9c576e93-6ae6-44ca-8e03-9d0deafd64bd.png)
**Maketda**
![image](https://user-images.githubusercontent.com/99461357/163166055-d9d41521-c8cf-4af0-a073-0767d5bc491d.png)

**Comment by akramjonnuriddinov** [comment]
#fixed
