### ISSUE TITLE
"detail.html" da `box-shadow:;`  stillari berilmagan.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#21]
**Sizda**
![image](https://user-images.githubusercontent.com/99461357/163167078-a88262d1-6d40-49cb-92be-aaead41a027f.png)
**Maketda**
![image](https://user-images.githubusercontent.com/99461357/163167385-992f6db7-531a-4942-ac67-3ac65366b565.png)

**Comment by akramjonnuriddinov** [comment]
#fixed
