### ISSUE TITLE
Google fonts ortiqchadur.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#22]
Agar siz @font-face dan foydalangan bo'lsangiz **Google fonts**  ortiqchadur..
![image](https://user-images.githubusercontent.com/99461357/163167763-bffd0042-1eb1-4948-b528-b36e22baa670.png)
<<<<<<detail.html>>>>>>> da

**Comment by akramjonnuriddinov** [comment]
`font-weight: 800;` degan qiymat @font-face orqali ulanganda ishlamadi. Shunga google fontsdan font-weight: 800; bo'lganini olib keldim

**Comment by MIRZOULUGBEK9008** [comment]
> `font-weight: 800;` degan qiymat @font-face orqali ulanganda ishlamadi. Shunga google fontsdan font-weight: 800; bo'lganini olib keldim

Ishlashi kerak, balki ulanisgda xatolik bordir.
Ishlamaganiga dalil bormi ?
