### ISSUE TITLE
@font-face  "comment"  holatida bo'lmasligi kerak

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#3]
sababi ushbu turkum ham saytda foydalanilgan...
![image](https://user-images.githubusercontent.com/99461357/163147017-1f2f886d-02b1-4c92-89b3-cecf3d71c7ea.png)

**Comment by akramjonnuriddinov** [comment]
link orqali ulaganim borligini uchun font-weight: 800; bo'lgan qiymatni commentga olib qo'yganman
