### ISSUE TITLE
Imlodagi xato.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [akramjonnuriddinov/001-countries#7]
**Sizda**
![image](https://user-images.githubusercontent.com/99461357/163155292-ab61fbdf-8821-4294-b389-a15c84ee06f8.png)
**Aslida**
_Add "white-space: no-wrap;  into .header-title_

**Comment by akramjonnuriddinov** [comment]
Yo'q shunaqa bo'ladi.)
